# Generated by Django 5.1.4 on 2024-12-09 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblMaster',
            fields=[
                ('num', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('tdata', models.TextField()),
                ('order_no', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tbl_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSchoolid',
            fields=[
                ('id', models.SmallAutoField( primary_key=True, serialize=False)),
                ('s_id', models.TextField()),
                ('s_pass', models.TextField()),
                ('l_login_date', models.DateTimeField(blank=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'tbl_schoolid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCurriculum',
            fields=[
                ('id', models.SmallAutoField( primary_key=True, serialize=False)),
                ('curr_name', models.TextField()),
                ('sub_id', models.SmallIntegerField()),
                ('sub_name', models.TextField(blank=True, null=True)),
                ('next_num', models.SmallIntegerField(blank=True, default=1)),
                ('sub_enable', models.BooleanField(blank=True, default=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('s', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tblschoolid')),
            ],
            options={
                'db_table': 'tbl_curriculum',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCurrDetail',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sub_id', models.SmallIntegerField()),
                ('task_id', models.SmallIntegerField()),
                ('task_name', models.TextField()),
                ('next_num', models.SmallIntegerField()),
                ('task_enable', models.BooleanField(default=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('curr', models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='core.tblcurriculum')),
                ('s', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tblschoolid')),
            ],
            options={
                'db_table': 'tbl_curr_detail',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSubject',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('sub_name', models.TextField()),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('s', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tblschoolid')),
            ],
            options={
                'db_table': 'tbl_subject',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTask',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('u_id', models.SmallIntegerField(null=True)),
                ('sub_id', models.SmallIntegerField()),
                ('task_id', models.SmallIntegerField()),
                ('status', models.SmallIntegerField(choices=[(0, '計画中'), (1, '実行中'), (2, '復習1回目'), (3, '復習2回目'), (4, '復習3回目'), (5, '復習4回目'), (6, '復習5回目'), (7, '復習6回目'), (8, '完全習得')], default=0)),
                ('grade', models.SmallIntegerField(choices=[(0, '未設定'), (1, 'A'), (2, 'B'), (3, 'C')],default=0)),
                ('priority', models.SmallIntegerField(choices=[(0, '未設定'), (1, 'A'), (2, 'B'), (3, 'C')],default=0)),
                ('tag', models.TextField(default='未設定')),
                ('deadline', models.DateField(blank=True,null=True)),
                ('number_1stchk', models.DateField(blank=True, db_column='1stCHK', null=True)),
                ('number_1streview', models.DateField(blank=True, db_column='1stReview', null=True)),
                ('number_2ndchk', models.DateField(blank=True, db_column='2ndCHK', null=True)),
                ('number_3rdchk', models.DateField(blank=True, db_column='3rdCHK',null=True)),
                ('number_4thchk', models.DateField(blank=True, db_column='4thCHK',null=True)),
                ('number_5thchk', models.DateField(blank=True, db_column='5thCHK',null=True)),
                ('number_6thchk', models.DateField(blank=True, db_column='6thCHK',null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True,null=True)),
                ('curr', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tblcurriculum')),
            ],
            options={
                'db_table': 'tbl_task',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTestname',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('dsp_order', models.SmallIntegerField()),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tblschoolid')),
            ],
            options={
                'db_table': 'tbl_testname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblUser',
            fields=[
                ('u_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('u_name', models.TextField()),
                ('u_pass', models.TextField()),
                ('u_auth', models.SmallIntegerField(choices=[(0, '生徒'), (1, '講師'), (2, '管理者')], default=0)),
                ('l_login_date', models.DateTimeField(auto_now=True, null=True)),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True,null=True)),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tblschoolid')),
            ],
            options={
                'db_table': 'tbl_user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblGrades',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField()),
                ('score', models.SmallIntegerField()),
                ('update_date', models.DateTimeField(auto_now=True, null=True)),
                ('reg_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('tst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tbltestname')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tbluser')),
            ],
            options={
                'db_table': 'tbl_grades',
                'managed': True,
            },
        ),
    ]
