# Generated by Django 5.1.4 on 2025-01-29 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcurrdetail',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblcurriculum',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblgrades',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblmaster',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblschoolid',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblsubject',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbltask',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbltestname',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tbluser',
            options={'managed': False},
        ),
    ]
