# Generated by Django 5.1.4 on 2025-01-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tblcurrdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblschoolid',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbluser',
            options={'managed': True},
        ),
    ]
