# Generated by Django 5.1.4 on 2025-01-29 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_tblschoolid_options_alter_tbluser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblschoolid',
            name='s_name',
            field=models.CharField(default='未設定', max_length=100),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='user_simei',
            field=models.CharField(default='未設定', max_length=100),
        ),
        migrations.AlterField(
            model_name='tblschoolid',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tblschoolid',
            name='l_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblschoolid',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tblschoolid',
            name='s_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tblschoolid',
            name='s_pass',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='l_login_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tblschoolid'),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='u_auth',
            field=models.SmallIntegerField(choices=[(-1, '保護者'), (0, '生徒'), (1, '講師'), (2, '教室')], default=0),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='u_id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='u_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='u_pass',
            field=models.TextField(),
        ),
    ]
