# Generated by Django 5.1.4 on 2025-04-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='l_login_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='u_auth',
            field=models.SmallIntegerField(choices=[(-1, '保護者'), (0, '生徒'), (1, '講師'), (2, '教室')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_simei',
            field=models.CharField(default='未設定', max_length=100),
        ),
    ]
